version: '3.7'

services:
  fluentd:
    name: sender_tail_fluentd
    image: fluent/fluentd:v1.3.2
    restart: always
    command: >
      /usr/bin/fluentd -c /fluentd/etc/sender_tail_file.conf -v
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - ${PWD}/log:/fluentd/log
      - ${PWD}/tmp/etc/sender_tail_file.conf:/fluentd/etc/sender_tail_file.conf:ro